version: "2"
services:
  tribune:
    image: docker.pkg.github.com/devnewton/jb3/jb3:latest
    ports:
    - "8080:8080"
    depends_on:
    - mongodb
  mongodb:
    image: mongo
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - "27017:27017"
